name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: freckle/stack-action@v4 # Includes stack build + stack test

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.5'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/
        fail-on: warning

        