name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.8.3' 
        enable-stack: true
        stack-version: 'latest'

    - name: 'Run tests'
      run: stack test

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.5'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/
        fail-on: warning

        